name: build and publish containers
on: [pull_check]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to dockerhub
      uses: docker/login-action@v1
      with:
        registry: hub.docker.com
        username: ysakashita
        password: ${{ secrets.DOCKERHUB }}
    - name: build and push
      id: build-push
      run: |
        IMAGE_TAG=latest
        VERSION=git-$(git rev-parse --short HEAD)
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          TAG=${GITHUB_REF#refs/tags/}
        fi
        make build
        make push
